import{a as S,S as v,i as c}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",P="52781164-186021ddb033549fd762d563f",u=15;async function M(t,r){const n={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:u};return(await S.get(q,{params:n})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load.btn"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250,close:!0});function C(t){const r=t.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:w})=>`
  <li class='gallery-item'>
  <a href='${s}'>
  <img src='${n}' alt='${e}' />
  </a>
  <div class='info'>
  <p class='info-item'><b>Likes:</b> ${o}</p>
  <p class='info-item'><b>Views:</b> ${a}</p>
  <p class='info-item'><b>Comments:</b> ${L}</p>
  <p class='info-item'><b>Downloads:</b> ${w}</p>
  </div>
  </li>
  `).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}function E(){m.innerHTML=""}function $(){f.classList.add("visible")}function k(){f.classList.remove("visible")}function R(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function x(){const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const p=document.querySelector(".form"),h=document.querySelector("input[name ='search-text']"),A=document.querySelector(".load.btn");h.removeAttribute("required");p.addEventListener("submit",O);A.addEventListener("click",I);let i=1,l=0,y="";async function b(){$(),d();try{const t=await M(y,i);if(i===1&&(l=Math.ceil(t.totalHits/u),!t.hits.length)){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",theme:"dark",backgroundColor:"red",messageSize:"16",timeout:5e3}),d();return}C(t.hits),i>1&&x(),i<l?R():i===l&&(d(),t.hits.length>0&&c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",theme:"dark",backgroundColor:"blue",messageSize:"16",timeout:5e3}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight",theme:"dark",backgroundColor:"red",timeout:5e3})}finally{k()}}async function O(t){t.preventDefault();const r=h.value.trim().toLowerCase();if(!r){c.warning({message:"Please enter a search term!",position:"topRight",theme:"dark",backgroundColor:"red"});return}i=1,l=0,y=r,E(),await b(),p.reset()}async function I(){i++,await b()}
//# sourceMappingURL=index.js.map
